import AppNodeTextKey from '@userscript/ui/appNode/AppNodeTextKey';

type TextKey = AppNodeTextKey | 'setting'
| 'font'
| 'color'
| 'ownerColor'
| 'moderatorColor'
| 'memberColor'
| 'feedback'
| 'eventLog'
| 'giveFeedback'
| 'chatOpacity'
| 'fontSize'
| 'fontWeight'
| 'shadowFontWeight'
| 'flowSpeed'
| 'maxChatCount'
| 'maxChatLength'
| 'laneCount'
| 'bannedWords'
| 'bannedWordRegexes'
| 'bannedUsers'
| 'simplifyChatField'
| 'createBanButton'
| 'displayModName'
| 'displaySuperChatAuthor'
| 'createChats'
| 'textOnly'
| 'error'
| 'video'
| 'chatField'
| 'useStepTiming'
| 'timingStepCount'
| 'chatFilter'
| 'flowChat'
| 'clearFlowChats'
| 'flowNewChatIf'
| 'noOverlap'
| 'minSpacing'
| 'fieldScale'
| 'copy'
| 'showChats'
| 'hideChats'
| 'flowY1'
| 'flowY2'
| 'flowX1'
| 'flowX2'
| 'shadowColor'
| 'logEvents'
| 'importLog';

export default TextKey;
