export default (currentFont: string): readonly (
readonly [string, string, string, string]
)[] => [
  ['', 'Default', 'デフォルト', 'Default'],
  ['arial', 'Arial', 'Arial', 'Arial'],
  ['arial black', 'Arial Black', 'Arial Black', 'Arial Black'],
  ['arial narrow', 'Arial Narrow', 'Arial Narrow', 'Arial Narrow'],
  ['Century', 'Century', 'Century', 'Century'],
  ['Comic Sans MS', 'Comic Sans MS', 'Comic Sans MS', 'Comic Sans MS'],
  ['Courier', 'Courier', 'Courier', 'Courier'],
  ['cursive', 'cursive', 'cursive', 'cursive'],
  ['fantasy', 'fantasy', 'fantasy', 'fantasy'],
  ['Impact', 'Impact', 'Impact', 'Impact'],
  ['Meiryo', 'Meiryo', 'メイリオ', 'Meiryo'],
  ['Meiryo UI', 'Meiryo UI', 'メイリオ UI', 'Meiryo UI'],
  ['monospace', 'monospace', 'monospace', 'monospace'],
  [
    'Monotype Corsiva',
    'Monotype Corsiva',
    'Monotype Corsiva',
    'Monotype Corsiva',
  ],
  ['MS PGothic', 'MS PGothic', 'MS Pゴシック', 'MS PGothic'],
  ['MS Gothic', 'MS Gothic', 'MS ゴシック', 'MS Gothic'],
  ['MS Sans Serif', 'MS Sans Serif', 'MS Sans Serif', 'MS Sans Serif'],
  ['MS Serif', 'MS Serif', 'MS Serif', 'MS Serif'],
  ['MS UI Gothic', 'MS UI Gothic', 'MS UI Gothic', 'MS UI Gothic'],
  ['sans-serif', 'Sans-serif', 'Sans-serif', 'Sans-serif'],
  ['serif', 'Serif', 'Serif', 'Serif'],
  ['Times New Roman', 'Times New Roman', 'Times New Roman', 'Times New Roman'],
  ['Yu Gothic', 'Yu Gothic', '遊ゴシック', 'Yu Gothic'],
  ['YuGothic', 'YuGothic', '游ゴシック体', 'YuGothic'],
  [currentFont, 'Custom', 'カスタム', '自定义'],
] as const;
